### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by ghostofadana** [NoeMoyen/LoL-LCU-Auto-Report#1]
can u do tutorial for me i cant understand how to open and use it, for example what i will write on game id teamid or not write i dont know anything

**Comment by ghostofadana** [comment]
edit* now i converted it exe but there is only one sentence on exe file "most racist tool" now what ill do 
![Screenshot_8](https://user-images.githubusercontent.com/125164348/218286980-d3e45f62-f955-4065-93b1-fc201aae7575.jpg)

**Comment by Momollax** [comment]
hello, first please pull, cause the message i put is verry dumb, and i apologise for it.
The bot will be activate when you finish your game. 
It will find the gameId, and will report everyone exept your friend, and yourself.
